version: '2'
services:
    node:
        container_name: node
        build: ./docker/node
        ports:
          - "80:80"
          - "3000:3000"
        volumes:
          - ./src:/var/www/html
        command: tail -f /dev/null