FROM node:latest
WORKDIR /var/www/html

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install tcpdump
RUN apt-get -y install unzip
RUN apt-get -y install less
RUN apt-get -y install vim
RUN apt-get -y install figlet
